#! /bin/bash
ifconfig mlan0 down
ifconfig uap0 down
ifconfig mmlan0 down
ifconfig muap0 down
ifconfig uap1 down
ifconfig muap1 down
ifconfig wfd0 down
ifconfig wfd1 down
ifconfig mwfd0 down
ifconfig mwfd1 down
for (( i = 0; i <= 30; i++ ))
do
    rmmod moal 2> /dev/null
    lsmod 2>&1 | grep moal > /dev/null
    if [ ! $? -eq 0 ]; then
        break
    fi
    sleep 1
done
rmmod mlan
sleep 5
