# Not matter how many spaces or tabs are inserted in a line,
# components and ending format must be exactly same as given
# example:
#
# 	<card_type>[_<block_id>] = {
# 		key=value
# 	}
#
# card_type	: 8XXX			          (mandatory)
# block_id	: configuration block id          (optional )
# key		: module parameter name
# value		: value for module parameter
#		for string value, no need to add ""
#
# card_type supported: 8887/8897/8997/8977/8987/9098
# block_id: support same chipset with
# different module parameter.
# For example to support mutiple SD8997 cards, usr can
# specify the configuration block id number [0 - 9], if not
# specified, it is taken as 0 by default.
#
# debug related module parameters could not be set via module
# configure file, ex. drvdbg could not be set in this file
#
# line started with "#" will be ignored
# refer to the USB8997_1 for parameters that could be set in
# this configuration file, and set the corresponding value
# according to your real needs

SD8997 = {
	txpwrlimit_cfg=nxp/rgpower_8997.bin
	cal_data_cfg=none
}
SD8987 = {
	txpwrlimit_cfg=nxp/rgpower_8987.bin
	cal_data_cfg=none
}
PCIE8997 = {
	txpwrlimit_cfg=nxp/rgpower_8997.bin
	cal_data_cfg=none
}

PCIE9098_0 = {
	txpwrlimit_cfg=nxp/rgpower_9098.bin
}

PCIE9098_1 = {
	txpwrlimit_cfg=nxp/rgpower_9098.bin
}

PCIEAW693_0 = {
	txpwrlimit_cfg=nxp/aw693_rgpower_WW_V3_1.bin
}

PCIEAW693_1 = {
	txpwrlimit_cfg=nxp/aw693_rgpower_WW_V3_1.bin
}

SDAW693_0 = {
	txpwrlimit_cfg=nxp/aw693_rgpower_WW_V3_1.bin
}

SDAW693_1 = {
	txpwrlimit_cfg=nxp/aw693_rgpower_WW_V3_1.bin
}

SD9098_0 = {
	txpwrlimit_cfg=nxp/rgpower_9098.bin
}

SD9098_1 = {
	txpwrlimit_cfg=nxp/rgpower_9098.bin
}

SDIW416 = {
	cal_data_cfg=none
	txpwrlimit_cfg=nxp/rgpower_iw416.bin
}

SD8801 = {
}

SDIW610 = {
	txpwrlimit_cfg=nxp/iw610_rgpower_WW_V3_1.bin
}

USBIW610 = {
	txpwrlimit_cfg=nxp/iw610_rgpower_WW_V3_1.bin
}

SDIW612 = {
	txpwrlimit_cfg=nxp/rgpower_IW612.bin
}
